---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vmware
  vcenter_hostname: 192.168.1.100
  vcenter_username: administrator@easlab.co.uk
  vcenter_password: ${VCENTER_PASSWORD}
  validate_certs: false
  datacenter: Cardiff
  esxi_hostname: 192.168.1.102
  folder: /Ansible/molecule
  vm_username: ${USER}
  vm_password: ${VCENTER_PASSWORD}
  instance_os_type: linux # is possible only specify [linux or windows]
  # The below are possible parameters to be specified if using the windows template.
  #winrm_port: 5986 # is WinRM port
  #connection: winrm # is the connection type
  #winrm_transport: ntlm # is the authentication type
  #winrm_server_cert_validation: ignore # is the server certificate validation mode
  # The below list is possible to define DNS nameservers
platforms:
  - name: max-api # is an instance name
    template: RHEL79-Thin # is to be used as a template when cloning an instance
    #resource_pool: change me to resource pool
    #snapshot_src: change me to snapshot name # is a snapshot name to be possible specified if you want to use linked clone.
    hardware:
      num_cpus: 2 # is cpu number to be configured to an instance
      memory_mb: 2048 # is memory size(MB) to be configured to an instance
    networks:
      - name: VM Network # is a port group to be assigned to an instance
        type: dhcp

    group: nexus
provisioner:
  name: ansible
verifier:
  name: ansible
